name: CD for backend app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install pipenv
        run: pip install pipenv

      - name: install dependencies
        run: pipenv install

      - name: run lint
        run: pipenv run lint

  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup python
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install pipenv
      run: pip install pipenv

    - name: install dependencies
      run: pipenv install

    - name: run test
      run: pipenv run test
  
  Build:
    needs: [Lint,Test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: use python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: push docker 
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 157277462905.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
        docker push 157277462905.dkr.ecr.us-east-1.amazonaws.com/backend:latest
  
    - name: deloy to eks
      working-directory: ./starter/backend/k8s
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1
        kustomize edit set image backend=157277462905.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        kustomize build | kubectl apply -f -
