name: CD for backend app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install pipenv
        run: pip install pipenv

      - name: install dependencies
        run: pipenv install

      - name: run lint
        run: pipenv run lint
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install pipenv
      run: pip install pipenv

    - name: install dependencies
      run: pipenv install

    - name: run test
      run: pipenv run test
  
  Build:
    needs: [Lint,Test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      
    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install

    - name: Build and Push Docker Image
      run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 .